import Link from "next/link";
import { TopNavBar } from "../components/sections/TopNavBar";
import { Footer } from "../components/sections/Footer";

export const metadata = {
  title: "Privacy Notice — FundBrave",
  description: "How FundBrave handles information in connection with the Logos Circle fundraising campaign.",
};

const sections = [
  {
    number: "1",
    title: "Information We Collect",
    content: (
      <>
        <p className="text-white/60 leading-relaxed mb-4">
          Fundbrave does not intentionally collect personal data from individuals participating
          in this fundraising campaign. However, limited information may be processed in the
          following situations:
        </p>
        <ul className="space-y-2">
          {[
            "When donations are made through third-party payment providers",
            "When individuals voluntarily contact us via email or messaging platforms",
            "When basic technical information (such as IP address or browser type) is automatically generated by websites or payment systems",
          ].map((item) => (
            <li key={item} className="flex gap-3 text-white/60 text-sm leading-relaxed">
              <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-[#2563EB] flex-shrink-0" />
              {item}
            </li>
          ))}
        </ul>
      </>
    ),
  },
  {
    number: "2",
    title: "How We Use Information",
    content: (
      <>
        <p className="text-white/60 leading-relaxed mb-4">
          Any information received is used strictly for:
        </p>
        <ul className="space-y-2 mb-4">
          {[
            "Processing and confirming donations",
            "Responding to inquiries or support requests",
            "Maintaining the security and integrity of our fundraising activities",
          ].map((item) => (
            <li key={item} className="flex gap-3 text-white/60 text-sm leading-relaxed">
              <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-[#2563EB] flex-shrink-0" />
              {item}
            </li>
          ))}
        </ul>
        <p className="text-white/60 leading-relaxed">
          We do not sell, rent, or share personal information with third parties for marketing purposes.
        </p>
      </>
    ),
  },
  {
    number: "3",
    title: "Third-Party Services",
    content: (
      <p className="text-white/60 leading-relaxed">
        Donations may be processed through trusted third-party payment platforms. These providers
        may collect and process personal information in accordance with their own privacy policies.
        Fundbrave does not control how these third parties handle data.
      </p>
    ),
  },
  {
    number: "4",
    title: "Data Security",
    content: (
      <p className="text-white/60 leading-relaxed">
        We take reasonable steps to protect any information associated with our fundraising
        activities from unauthorized access, misuse, or disclosure.
      </p>
    ),
  },
  {
    number: "5",
    title: "Data Retention",
    content: (
      <p className="text-white/60 leading-relaxed">
        We retain information only for as long as necessary to fulfill the purpose for which
        it was received, comply with legal obligations, or resolve disputes.
      </p>
    ),
  },
  {
    number: "6",
    title: "Your Rights",
    content: (
      <p className="text-white/60 leading-relaxed">
        Individuals who have shared information with Fundbrave may request access to, correction
        of, or deletion of their information by contacting us using the details below.
      </p>
    ),
  },
  {
    number: "7",
    title: "Contact Information",
    content: (
      <>
        <p className="text-white/60 leading-relaxed mb-3">
          If you have any questions about this Privacy Notice or our fundraising campaign,
          please contact:
        </p>
        <div className="glass rounded-xl p-4 inline-flex flex-col gap-1">
          <span className="text-white/40 text-xs uppercase tracking-widest">Email</span>
          <a
            href="mailto:info@fundbrave.com"
            className="text-[#2563EB] hover:text-blue-400 transition-colors font-medium"
          >
            info@fundbrave.com
          </a>
          <span className="text-white/40 text-xs uppercase tracking-widest mt-2">Organisation</span>
          <span className="text-white/80 font-medium">Fundbrave</span>
        </div>
        <p className="text-white/40 text-sm mt-4 leading-relaxed">
          We may update this Privacy Notice from time to time. Any changes will be communicated
          through our official communication channels.
        </p>
      </>
    ),
  },
];

export default function PrivacyPage() {
  return (
    <>
      <TopNavBar />
      <main className="min-h-screen bg-[#0A0E1A] pt-32 pb-24">
        <div className="max-w-3xl mx-auto px-6">

          {/* Header */}
          <div className="mb-16">
            <div className="flex items-center gap-3 mb-6">
              <div className="w-10 h-10 rounded-xl bg-[#2563EB]/10 border border-[#2563EB]/20 flex items-center justify-center">
                <span className="material-symbols-outlined text-[#2563EB] text-xl">shield</span>
              </div>
              <span className="text-[#2563EB] text-sm font-semibold uppercase tracking-widest">
                Legal
              </span>
            </div>
            <h1 className="text-4xl md:text-5xl font-black text-white mb-4 leading-tight">
              Privacy Notice
            </h1>
            <p className="text-white/50 text-lg leading-relaxed">
              Fundbrave is committed to protecting the privacy of individuals who support our
              fundraising activities. This Notice explains how we handle information in
              connection with the Logos Circle campaign.
            </p>
            <div className="mt-6 flex items-center gap-2 text-white/30 text-sm">
              <span className="material-symbols-outlined text-base">update</span>
              Last updated April 2026
            </div>
          </div>

          {/* On-chain transparency notice */}
          <div className="glass rounded-2xl p-5 mb-12 border border-amber-500/20 bg-amber-500/5">
            <div className="flex gap-3">
              <span className="material-symbols-outlined text-amber-400 text-xl flex-shrink-0 mt-0.5">
                info
              </span>
              <div>
                <p className="text-amber-400 font-semibold text-sm mb-1">On-chain transparency</p>
                <p className="text-white/50 text-sm leading-relaxed">
                  This campaign runs on the Base blockchain. Donation amounts, wallet addresses,
                  and timestamps are permanently public on-chain. This is a feature of blockchain
                  fundraising — donors can independently verify every transaction — but it means
                  wallet addresses cannot be made private after a donation is confirmed.
                </p>
              </div>
            </div>
          </div>

          {/* Sections */}
          <div className="space-y-8">
            {sections.map((section) => (
              <div key={section.number} className="glass rounded-2xl p-8">
                <div className="flex items-start gap-4 mb-4">
                  <span className="w-8 h-8 rounded-lg bg-[#2563EB]/10 border border-[#2563EB]/20 flex items-center justify-center text-[#2563EB] font-bold text-sm flex-shrink-0">
                    {section.number}
                  </span>
                  <h2 className="text-xl font-bold text-white pt-1">{section.title}</h2>
                </div>
                <div className="pl-12">{section.content}</div>
              </div>
            ))}
          </div>

          {/* Footer note */}
          <div className="mt-12 text-center">
            <p className="text-white/30 text-sm">
              By using this site you agree to this Privacy Notice and the responsible use of
              information related to your visit.
            </p>
            <Link
              href="/"
              className="inline-flex items-center gap-2 mt-6 text-[#2563EB] hover:text-blue-400 transition-colors text-sm font-medium"
            >
              <span className="material-symbols-outlined text-base">arrow_back</span>
              Back to campaign
            </Link>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
